### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by gary-van-woerkens** [SocialGouv/enfants-du-spectacle#636]
Apporter les modifications suivantes sur l'application principale **et** sur le formulaire:
- [x] remplacer au niveau du header le logo du préfet par le logo de la République Française (comme sur CDTN)
- [x] remplacer au niveau du footer le logo du préfet par le logo du Ministère du travail et de l'emploi (comme sur CDTN)
- [x] retirer le bloc partenaires avec le logo de beta.gouv

**Comment by gary-van-woerkens** [comment]
Pour information: on peut pas choisir l'emplacement des retours à a ligne dans les logos.

**Comment by gary-van-woerkens** [comment]
Note pour plus tard...

- Utilisation de `@dataesr/react-dsfr`, une librairie obsolète pour gérer le DSFR
- Utilisation d'une version ancienne de node `v14.18.0`
- Utilisation de `Procfile` qui ne sert probablement à rien (déploiement Heroku ?)
- Dead code (`./formulaire/styles`, ... )

**Comment by FJEANNOT** [comment]
https://github.com/SocialGouv/support/issues/661
